[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "synthyverse"
dynamic = ["version"]
description = "Synthetic data generation and evaluation library"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Jim Achterberg", email = " " },
    { name = "Saif Ul Islam", email = " " },
    { name = "Zia Ur Rehman", email = " " }
]
requires-python = ">=3.8"
dependencies = [
    "arfpy",
    "pandas",
    "synthcity",
    "ctgan",
    "torch",
    "numpy",
    "scikit-learn",
    "xgboost",
    "sdmetrics"
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.dynamic]
version = {attr = "synthyverse.__version__"}
